//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by excal.rc
//
#define T_NULL                          0
#define H_NULL                          1
#define T_SIN                           2
#define H_SIN                           3
#define T_COS                           4
#define H_COS                           5
#define T_TAN                           6
#define H_TAN                           7
#define T_HYP                           8
#define H_HYP                           9
#define T_ASIN                          10
#define H_ASIN                          11
#define T_ACOS                          12
#define H_ACOS                          13
#define T_ATAN                          14
#define H_ATAN                          15
#define T_ABS                           16
#define H_ABS                           17
#define T_XX                            18
#define H_XX                            19
#define T_SQRT                          20
#define H_SQRT                          21
#define T_INV                           22
#define H_INV                           23
#define T_POW10                         24
#define H_POW10                         25
#define T_EXP                           26
#define H_EXP                           27
#define T_LN                            28
#define H_LN                            29
#define T_LOG                           30
#define H_LOG                           31
#define T_FACT                          32
#define H_FACT                          33
#define T_POW                           34
#define H_POW                           35
#define T_INT                           36
#define H_INT                           37
#define T_FRAC                          38
#define H_FRAC                          39
#define T_RAND                          40
#define H_RAND                          41
#define T_COMB                          42
#define H_COMB                          43
#define T_PERM                          44
#define H_PERM                          45
#define T_PI                            46
#define H_PI                            47
#define T_CONST                         48
#define H_CONST                         49
#define T_SUMP                          50
#define H_SUMP                          51
#define T_SUMM                          52
#define H_SUMM                          53
#define T_SUMC                          54
#define H_SUMC                          55
#define T_SUMN                          56
#define H_SUMN                          57
#define T_SUMSDX                        58
#define H_SUMSDX                        59
#define T_SUMPDX                        60
#define H_SUMPDX                        61
#define H_SUMSDY                        62
#define H_SUMPDY                        63
#define T_MEANX                         64
#define H_MEANX                         65
#define T_MEANY                         66
#define H_MEANY                         67
#define T_SUMX                          68
#define H_SUMX                          69
#define T_SUMY                          70
#define H_SUMY                          71
#define T_SUMXX                         72
#define H_SUMXX                         73
#define T_SUMYY                         74
#define H_SUMYY                         75
#define T_SUMXY                         76
#define H_SUMXY                         77
#define T_CORR                          78
#define H_CORR                          79
#define T_YINT                          80
#define H_YINT                          81
#define T_SLOPE                         82
#define H_SLOPE                         83
#define T_ESTX                          84
#define H_ESTX                          85
#define T_ESTY                          86
#define H_ESTY                          87
#define T_TAX                           88
#define H_TAX                           89
#define T_PERC                          90
#define H_PERC                          91
#define T_PERCC                         92
#define H_PERCC                         93
#define T_CLRF                          94
#define H_CLRF                          95
#define T_STOFN                         96
#define H_STOFN                         97
#define T_RCLFN                         98
#define H_RCLFN                         99
#define T_FINN                          100
#define H_FINN                          101
#define ID_CURRENCY_BOX1                101
#define TRACE_PROGRAM                   101
#define T_INTR                          102
#define ID_CURRENCY_A_TO_B              102
#define H_INTR                          103
#define ID_CURRENCY_CANCEL              103
#define T_FINPV                         104
#define ID_CURRENCY_REDEFINE            104
#define TRACE_REGS                      104
#define TRACE_REGS2                     104
#define H_FINPV                         105
#define ID_CURRENCY_BOX2                105
#define TRACE_REGS1                     105
#define T_FINPMT                        106
#define ID_CURRENCY_B_TO_A              106
#define H_FINPMT                        107
#define T_FINFV                         108
#define H_FINFV                         109
#define T_AMORT                         110
#define H_AMORT                         111
#define T_DIV12                         112
#define H_DIV12                         113
#define T_MUL12                         114
#define H_MUL12                         115
#define T_DIV100                        116
#define H_DIV100                        117
#define T_MUL100                        118
#define H_MUL100                        119
#define T_FVPMT                         120
#define H_FVPMT                         121
#define T_CONV                          122
#define H_KG_LB                         123
#define T_KG_LB                         124
#define H_LB_KG                         125
#define T_LB_KG                         126
#define H_CE_FA                         127
#define T_CE_FA                         128
#define H_FA_CE                         129
#define T_FA_CE                         130
#define H_IN_CM                         131
#define T_IN_CM                         132
#define H_CM_IN                         133
#define T_CM_IN                         134
#define H_GR_OZ                         135
#define T_GR_OZ                         136
#define H_OZ_GR                         137
#define T_OZ_GR                         138
#define H_GA_LI                         139
#define T_GA_LI                         140
#define H_LI_GA                         141
#define T_LI_GA                         142
#define H_FT_MI                         143
#define T_FT_MI                         144
#define H_MI_FT                         145
#define T_MI_FT                         146
#define H_MI_KM                         147
#define T_MI_KM                         148
#define H_KM_MI                         149
#define T_KM_MI                         150
#define H_JO_CA                         151
#define T_JO_CA                         152
#define H_CA_JO                         153
#define T_CA_JO                         154
#define H_HMS                           155
#define T_HMS                           156
#define H_HR                            157
#define T_HR                            158
#define H_DE_RA                         159
#define T_DE_RA                         160
#define H_RA_DE                         161
#define T_RA_DE                         162
#define H_RE_PO                         163
#define T_RE_PO                         164
#define H_PO_RE                         165
#define T_PO_RE                         166
#define H_FT_FA                         167
#define T_FT_FA                         168
#define H_FA_FT                         169
#define T_FA_FT                         170
#define H_FT_ME                         171
#define T_FT_ME                         172
#define H_ME_FT                         173
#define T_ME_FT                         174
#define H_SI_SC                         175
#define T_SI_SC                         176
#define H_SC_SI                         177
#define T_SC_SI                         178
#define H_SF_SM                         179
#define T_SF_SM                         180
#define H_SM_SF                         181
#define T_SM_SF                         182
#define H_CI_CC                         183
#define T_CI_CC                         184
#define H_CC_CI                         185
#define T_CC_CI                         186
#define H_CF_CM                         187
#define T_CF_CM                         188
#define H_CM_CF                         189
#define T_CM_CF                         190
#define H_FO_ML                         191
#define T_FO_ML                         192
#define H_ML_FO                         193
#define T_ML_FO                         194
#define H_AT_PSI                        195
#define T_AT_PSI                        196
#define H_PSI_AT                        197
#define T_PSI_AT                        198
#define H_ACR_FT2                       199
#define T_ACR_FT2                       200
#define H_FT2_ACR                       201
#define T_FT2_ACR                       202
#define T_DEC                           203
#define H_DEC                           204
#define T_HEX                           205
#define H_HEX                           206
#define T_BIN                           207
#define H_BIN                           208
#define T_OCT                           209
#define H_OCT                           210
#define T_HEXA                          211
#define T_HEXB                          212
#define T_HEXC                          213
#define T_HEXD                          214
#define T_HEXE                          215
#define T_HEXF                          216
#define H_HEXDIG                        217
#define T_AND                           218
#define H_AND                           219
#define T_OR                            220
#define H_OR                            221
#define T_NOT                           222
#define H_NOT                           223
#define T_NAND                          224
#define H_NAND                          225
#define T_NOR                           226
#define H_NOR                           227
#define T_XOR                           228
#define H_XOR                           229
#define T_SL                            230
#define H_SL                            231
#define T_SR                            232
#define H_SR                            233
#define T_RL                            234
#define H_RL                            235
#define T_RR                            236
#define H_RR                            237
#define T_ASCII                         238
#define H_ASCII                         239
#define T_MOD                           240
#define H_MOD                           241
#define T_BINH                          242
#define H_BINH                          243
#define T_BINL                          244
#define H_BINL                          245
#define T_SLM                           246
#define H_SLM                           247
#define T_SRM                           248
#define H_SRM                           249
#define T_CIRCC                         250
#define H_CIRCC                         251
#define T_CIRCA                         252
#define H_CIRCA                         253
#define T_ELIPA                         254
#define H_ELIPA                         255
#define T_TRIA                          256
#define H_TRIA                          257
#define T_RECTC                         258
#define H_RECTC                         259
#define T_RECTA                         260
#define H_RECTA                         261
#define T_BOXA                          262
#define H_BOXA                          263
#define T_BOXV                          264
#define H_BOXV                          265
#define T_SPHA                          266
#define H_SPHA                          267
#define T_SPHV                          268
#define H_SPHV                          269
#define T_CYLA                          270
#define H_CYLA                          271
#define T_CYLV                          272
#define H_CYLV                          273
#define T_CONA                          274
#define H_CONA                          275
#define T_CONEV                         276
#define H_CONEV                         277
#define T_QUAD                          278
#define H_QUAD                          279
#define T_PYTHAG                        280
#define H_PYTHAG                        281
#define T_PRIME                         282
#define H_PRIME                         283
#define T_RESIST                        284
#define H_RESIST                        285
#define T_CAPS                          286
#define H_CAPS                          287
#define T_ELEMENT                       288
#define H_ELEMENT                       289
#define T_CPLXADD                       290
#define H_CPLXADD                       291
#define T_CPLXSUB                       292
#define H_CPLXSUB                       293
#define T_CPLXDIV                       294
#define H_CPLXDIV                       295
#define T_CPLXMUL                       296
#define H_CPLXMUL                       297
#define T_PERCT                         300
#define H_PERCT                         301
#define T_DATE                          302
#define H_DATE                          303
#define T_DAYS                          304
#define H_DAYS                          305
#define T_HERO                          306
#define H_HERO                          307
#define T_PREFIX                        308
#define H_PREFIX                        309
#define T_FMODE                         310
#define H_FMODE                         311
#define T_BOND                          312
#define H_BOND                          313
#define T_YTM                           314
#define H_YTM                           315
#define T_TODAY                         316
#define H_TODAY                         317
#define T_DMODE                         318
#define T_DEPR                          318
#define H_DMODE                         319
#define H_DEPR                          319
#define T_CF0                           320
#define H_CF0                           321
#define T_CFJ                           322
#define H_CFJ                           323
#define T_NPV                           324
#define H_NPV                           325
#define T_IRR                           326
#define H_IRR                           327
#define T_MUC                           328
#define H_MUC                           329
#define T_MUP                           330
#define H_MUP                           331
#define T_COST                          332
#define H_COST                          333
#define T_PRICE                         334
#define H_PRICE                         335
#define T_CPLXSIN                       336
#define H_CPLXSIN                       337
#define T_CPLXCOS                       338
#define H_CPLXCOS                       339
#define T_CPLXTAN                       340
#define H_CPLXTAN                       341
#define T_CPLXASIN                      342
#define H_CPLXASIN                      343
#define T_CPLXACOS                      344
#define H_CPLXACOS                      345
#define T_CPLXATAN                      346
#define H_CPLXATAN                      347
#define T_CONJ                          348
#define H_CONJ                          349
#define T_CPLXEXP                       350
#define H_CPLXEXP                       351
#define T_CPLXLN                        352
#define H_CPLXLN                        353
#define T_CPLXLOG                       354
#define H_CPLXLOG                       355
#define T_CPLXPOW                       356
#define H_CPLXPOW                       357
#define T_CPLXSQRT                      358
#define H_CPLXSQRT                      359
#define T_CPLXABS                       360
#define H_CPLXABS                       361
#define T_RLX                           362
#define H_RLX                           363
#define T_RRX                           364
#define H_RRX                           365
#define T_ASR                           366
#define H_ASR                           367
#define T_NUMBITS                       368
#define H_NUMBITS                       369
#define T_SETBIT                        370
#define H_SETBIT                        371
#define T_CLRBIT                        372
#define H_CLRBIT                        373
#define T_MASKL                         374
#define H_MASKL                         375
#define T_MASKR                         376
#define H_MASKR                         377
#define T_WORDSIZE                      378
#define H_WORDSIZE                      379
#define T_CPLXCHS                       380
#define H_CPLXCHS                       381
#define H_ATLAS                         382
#define T_ROUND                         383
#define H_ROUND                         384
#define T_FLOOR                         385
#define H_FLOOR                         386
#define T_CEIL                          387
#define H_CEIL                          388
#define T_GCD                           389
#define H_GCD                           390
#define T_LCM                           391
#define H_LCM                           392
#define T_MINR                          393
#define H_MINR                          394
#define ID_CARRY_POS                    395
#define T_MAXR                          395
#define H_MAXR                          396
#define T_ROUNDYX                       397
#define H_ROUNDYX                       398
#define T_2COMP                         399
#define H_2COMP                         400
#define T_MINW                          401
#define H_MINW                          402
#define T_MAXW                          403
#define H_MAXW                          404
#define T_CURRENCY                      405
#define H_CURRENCY                      406
#define T_LOG2                          407
#define H_LOG2                          408
#define T_MIRROR                        409
#define H_MIRROR                        410
#define T_TIMERSTART                    411
#define H_TIMERSTART                    412
#define T_TIMERSTOP                     413
#define H_TIMERSTOP                     414
#define T_TIMERCLEAR                    415
#define H_TIMERCLEAR                    416
#define T_ASTRO                         417
#define H_ASTRO                         418
#define T_IEEE                          419
#define H_IEEE                          420
#define T_PYRA                          421
#define H_PYRA                          422
#define T_PYRV                          423
#define H_PYRV                          424
#define T_ICIRC                         425
#define H_ICIRC                         426
#define T_MOLES                         427
#define H_MOLES                         428
#define T_MOLECULES                     429
#define H_MOLECULES                     430
#define T_GASVOL                        431
#define H_GASVOL                        432
#define T_OHMSE                         433
#define H_OHMSE                         434
#define T_OHMSI                         435
#define H_OHMSI                         436
#define T_OHMSR                         437
#define H_OHMSR                         438
#define T_GRAVITATION                   439
#define H_GRAVITATION                   440
#define T_ENERGY                        441
#define H_ENERGY                        442
#define T_CENTFORCE                     443
#define H_CENTFORCE                     444
#define T_CENTACCEL                     445
#define H_CENTACCEL                     446
#define T_ACCELDIST                     447
#define H_ACCELDIST                     448
#define T_PROJRANGE                     449
#define H_PROJRANGE                     450
#define T_PROJHEIGHT                    451
#define H_PROJHEIGHT                    452
#define T_RECALLN                       453
#define H_RECALLN                       454
#define T_STOREN                        455
#define H_STOREN                        456
#define T_GA_CM3                        457
#define H_GA_CM3                        458
#define T_PINT_LI                       459
#define H_PINT_LI                       460
#define T_IGA_LI                        461
#define H_IGA_LI                        462
#define T_FA_KE                         463
#define H_FA_KE                         464
#define T_IN_MM                         465
#define H_IN_MM                         466
#define T_FT_KM                         467
#define H_FT_KM                         468
#define T_KMH_MPS                       469
#define H_KMH_MPS                       470
#define T_KNOT_MPH                      471
#define H_KNOT_MPH                      472
#define T_AH_COL                        473
#define H_AH_COL                        474
#define T_AH_FAR                        475
#define H_AH_FAR                        476
#define T_HP_KW                         477
#define H_HP_KW                         478
#define T_CONV_INV                      479
#define H_CONV_INV                      480
#define T_VECTADD                       481
#define H_VECTADD                       482
#define T_VECTSUB                       483
#define H_VECTSUB                       484
#define T_VECTCROSS                     485
#define H_VECTCROSS                     486
#define T_VECTDOT                       487
#define H_VECTDOT                       488
#define T_VECTANGLE                     489
#define H_VECTANGLE                     490
#define T_VECTCONVERTR                  491
#define H_VECTCONVERTR                  492
#define T_VECTCONVERTP                  493
#define H_VECTCONVERTP                  494
#define T_MIL_MM                        495
#define H_MIL_MM                        496
#define T_CFNJ                          497
#define H_CFNJ                          498
#define T_SPPV                          499
#define H_SPPV                          500
#define T_SPFV                          501
#define H_SPFV                          502
#define T_USPV                          503
#define H_USPV                          504
#define T_USFV                          505
#define H_USFV                          506
#define T_INFL                          507
#define H_INFL                          508
#define T_EFF                           509
#define H_EFF                           510
#define T_LBLA                          511
#define T_LBLB                          512
#define T_LBLC                          513
#define H_LABELS                        514
#define T_GOTOA                         515
#define H_GOTOS                         516
#define T_MACXLY                        517
#define H_MACXLY                        518
#define T_MACXGY                        519
#define H_MACXGY                        520
#define T_GOTOB                         521
#define T_XLEZERO                       522
#define H_XLEZERO                       523
#define T_XGTZERO                       524
#define H_XGTZERO                       525
#define T_XEY                           526
#define H_XEY                           527
#define T_XNEY                          528
#define H_XNEY                          529
#define T_XEZERO                        530
#define H_XEZERO                        531
#define T_XNEZERO                       532
#define H_XNEZERO                       533
#define T_LBLD                          534
#define T_LBLE                          535
#define T_LBLF                          536
#define T_LBLG                          537
#define T_LBLH                          538
#define T_GOTOC                         539
#define T_GOTOD                         540
#define T_GOTOE                         541
#define T_GOTOF                         542
#define T_GOTOG                         543
#define T_GOTOH                         544
#define T_GSBA                          545
#define H_GOSUBS                        546
#define T_GSBB                          547
#define T_GSBC                          548
#define T_RETURN                        549
#define H_RETURN                        550
#define T_GSBD                          551
#define T_GSBE                          552
#define T_GSBF                          553
#define T_GSBG                          554
#define T_SFX                           555
#define H_SFX                           556
#define T_CFX                           557
#define H_CFX                           558
#define T_TFX                           559
#define H_TFX                           560
#define T_PAUSE                         561
#define H_PAUSE                         562
#define T_INPA                          563
#define H_INPA                          564
#define T_INPB                          565
#define H_INPB                          566
#define T_BST                           567
#define H_BST                           568
#define T_TRACE                         569
#define H_TRACE                         570
#define T_FWD                           571
#define H_FWD                           572
#define T_REV                           573
#define H_REV                           574
#define H_MEDIT                         575
#define T_DEL                           576
#define H_DEL                           577
#define T_MEDIT                         578
#define T_LEDZEP                        579
#define T_LBLI                          580
#define T_GOTOI                         581
#define T_GSBI                          582
#define T_GSBH                          583
#define T_LBLJ                          584
#define T_GOTOJ                         585
#define T_GSBJ                          586
#define T_LBLK                          587
#define T_GOTOK                         588
#define T_GSBK                          589
#define T_INPC                          590
#define H_INPC                          591
#define T_INPD                          592
#define H_INPD                          593
#define T_STOC                          594
#define H_STOC                          595
#define T_STOD                          596
#define H_STOD                          597
#define T_RCLC                          598
#define H_RCLC                          599
#define T_RCLD                          600
#define H_RCLD                          601
#define T_STOIND                        602
#define H_STOIND                        603
#define T_GOTOIND                       604
#define H_GOTOIND                       605
#define T_GSBIND                        606
#define H_GSBIND                        607
#define T_RCLIND                        608
#define H_RCLIND                        609
#define T_HALT                          610
#define H_HALT                          611
#define T_LOOP                          612
#define H_LOOP                          613
#define T_SETLOOP                       614
#define H_SETLOOP                       615
#define T_STEP                          616
#define H_STEP                          617
#define T_DEBUG                         618
#define H_DEBUG                         619
#define T_STRACE                        620
#define H_STRACE                        621
#define T_LOOPA                         622
#define H_LOOPA                         623
#define T_LOOPB                         624
#define H_LOOPB                         625
#define T_LOOPC                         626
#define H_LOOPC                         627
#define T_LOOPD                         628
#define H_LOOPD                         629
#define T_LOOPE                         630
#define H_LOOPE                         631
#define T_LOOPF                         632
#define H_LOOPF                         633
#define T_LOOPG                         634
#define H_LOOPG                         635
#define T_LOOPH                         636
#define H_LOOPH                         637
#define T_LOOPJ                         638
#define H_LOOPJ                         639
#define T_JUMP                          640
#define H_JUMP                          641
#define T_STOE                          642
#define H_STOE                          643
#define T_RCLE                          644
#define H_RCLE                          645
#define T_STOF                          646
#define H_STOF                          647
#define T_RCLF                          648
#define H_RCLF                          649
#define T_STOG                          650
#define H_STOG                          651
#define T_RCLG                          652
#define H_RCLG                          653
#define T_STOH                          654
#define H_STOH                          655
#define T_RCLH                          656
#define H_RCLH                          657
#define T_SKIP                          658
#define T_DSZ                           658
#define H_SKIP                          659
#define H_DSZ                           659
#define T_TIMERPUSH                     660
#define H_TIMERPUSH                     661
#define T_STON_LB                       662
#define H_STON_LB                       663
#define T_LTON_LB                       664
#define H_LTON_LB                       665
#define T_MTON_LB                       666
#define H_MTON_LB                       667
#define T_LOOPI                         668
#define H_LOOPI                         669
#define H_LOOPK                         670
#define T_LOOPK                         671
#define T_CLEARF                        672
#define H_CLEARF                        673
#define T_STO2I                         674
#define H_STO2I                         675
#define T_RCL2I                         676
#define H_RCL2I                         677
#define IDC_FORMAT                      998
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define MACRO_LIST                      1004
#define IDC_EDIT3                       1004
#define IDC_EDIT4                       1005
#define IDC_RADIO1                      1006
#define IDC_EDIT5                       1006
#define IDC_RADIO2                      1007
#define IDC_RADIO3                      1008
#define IDC_RADIO4                      1009
#define IDC_RADIO5                      1010
#define IDC_RADIO6                      1011
#define IDC_RADIO7                      1012
#define IDC_RADIO8                      1013
#define IDC_RADIO9                      1014
#define IDC_RADIO10                     1015
#define IDC_RADIO11                     1016
#define IDC_RADIO12                     1017
#define IDC_RADIO0                      1018
#define IDC_DECIMAL_PLACES              1019
#define IDC_CHECK1                      1021
#define IDC_BUTTON1                     1022
#define IDC_CHECK2                      1022
#define IDC_BUTTON2                     1023
#define IDC_RICHEDIT1                   1023
#define IDC_CHECK3                      1023
#define IDC_BUTTON3                     1024
#define IDC_RICHEDIT2                   1024
#define IDC_CHECK4                      1024
#define IDC_BUTTON4                     1025
#define IDC_LIST1                       1026
#define IDC_LIST2                       1027
#define IDC_CHECKSUM1                   1028
#define IDC_CHECKSUM2                   1029
#define IDM_MACRO                       40003
#define IDM_COPYMACROTOCLIPBOARD        40005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
